--- 
abstract: run your very own IRC bot net
author: 
  - Andrew Sterling Hanenkamp C<< <hanenkamp@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Bot-Net
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  App::CLI: 0
  App::CLI::Command: 0
  App::CLI::Command::Help: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Data::Remember: 0.07
  File::Find::Rule: 0
  Hash::Merge: 0
  Log::Log4perl: 0
  POE: 0
  POE::Component::IRC: 0
  POE::Component::Server::IRC: 0
  POE::Declarative: 0.007
  POE::Declarative::Mixin: 0
  Readonly: 0
  Regexp::Common: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0
tests: t/*.t t/*/t/*.t
version: 0.1.0
